# Generated by Django 3.2.9 on 2021-12-06 14:54

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=Account.models.get_file_path),
        ),
    ]
